### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by chaewoong0407** [pdlma0904/today-flower-client#1]
1. 이벤트 e 형식 타입 선언 필요. 모르는 것은 any로 해도 상관없지만 다 선언이 가능한 부분이기에 타입 선언을 해준다.

example

pages/Cart.ts 

```
23번째 줄
  const handleAllChcked = (e: any) => {
    // 체크할 시 checkedList id 값 전체 넣기, 체크 해제할 시 CheckList에 빈 배열 넣기
    setCheckedList(e.target.checked ? IdList : [])
  };

68번째 줄

              <input
                type="checkbox"
                onChange={handleAllChcked}
                checked={checkedList.length === IdList.length}
              />
```
해당 부분을 바로
`
                onChange={(e) => setCheckedList(e.target.checked ? IdList : [])}
`
형식으로 교체해주면

<img width="378" alt="스크린샷 2021-05-18 오후 8 28 52" src="https://user-images.githubusercontent.com/48791625/118643551-ab24b400-b817-11eb-918a-80fc2c7e6134.png">

위와 같이 타입이 보인다. 이런 방식으로 모든 event에 타입선언을 해주면 좋을 것 같다.

2. components/Payment/Payment.ts 

형식을 맞춰주자. 다른 곳에서 React.FC를 사용했다면 여기서도 사용해주자.

3. DummyData는 Container 폴더를 거쳐 관리하자. Pages에서 Component로 넘어가기 전에 상태관리를 Container 폴더에서 할 것이다. 그러기 위해 자주 사용하는 Data가 아니라면 Container를 거쳐 관리하자.

좀만 있다가 봐서 추가 수정할 부분 있으면 또이슈 달아주겠습니다~

**Comment by pdlma0904** [comment]
감사합니다.
